# .github/release.yml

changelog:
  categories:
    - title: Core Breaking Changes
      labels:
        - Breaking Change
        - L.CAD Core
    - title: Core New Features
      labels:
        - New Feature
        - L.CAD Core
    - title: Core Improvements
      labels:
        - Improvement
        - L.CAD Core
    - title: Core Bug Fixes
      labels:
        - Bug Fixes
        - L.CAD Core
    - title: Core Documentation Changes
      labels:
        - Documentation
        - L.CAD Core
    - title: Core Unlabeled Changes (please categorize these)
      labels:
        - '*'
        - L.CAD Core

    - title: UI Breaking Changes
      labels:
        - Breaking Change
        - L.CAD UI
    - title: UI New Features
      labels:
        - New Feature
        - L.CAD UI
    - title: UI Improvements
      labels:
        - Improvement
        - L.CAD UI
    - title: UI Bug Fixes
      labels:
        - Bug Fixes
        - L.CAD UI
    - title: UI Documentation Changes
      labels:
        - Documentation
        - L.CAD UI
    - title: UI Unlabeled Changes (please categorize these)
      labels:
        - '*'
        - L.CAD UI

    - title: Skin Breaking Changes
      labels:
        - Breaking Change
        - L.CAD Skin
    - title: Skin New Features
      labels:
        - New Feature
        - L.CAD Skin
    - title: Skin Improvements
      labels:
        - Improvement
        - L.CAD Skin
    - title: Skin Bug Fixes
      labels:
        - Bug Fixes
        - L.CAD Skin
    - title: Skin Documentation Changes
      labels:
        - Documentation
        - L.CAD Skin
    - title: Skin Unlabeled Changes (please categorize these)
      labels:
        - '*'
        - L.CAD Skin

      exclude:
        labels:
          - Breaking Change
          - New Feature
          - Improvement
          - Bug Fixes
          - Documentation
          - L.CAD UI
          - L.CAD Skin
          - L.CAD Core
